apiVersion: v1
kind: Service  # The type of Kubernetes object being defined
metadata:
  name: backend-svc
  namespace: sproj-app
spec:           # Defines the desired state of the service.
  type: ClusterIP
  selector:     # Tells the service which pods it should route traffic to.
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
